### ISSUE TITLE
Seems the message handlers for subscribe are not run on a Vert.x event loop thread

### ISSUE THREAD

**Issue by RichardHightower** [nats-io/nats-java-vertx-client#44]
found an issue in the NATS Vert.x client. Seems the message handlers for subscribe are not run on a Vert.x event loop thread. I see it is running on a NATS thread (nats:3 thread). In my view, the subscriber handler should run on the verticle context that subscribed. Or at least that is how other http servers or messaging clients work with Vert.x.

**Comment by RichardHightower** [comment]
```

, found an issue in the NATS Vert.x client. Seems the message handlers for subscribe are not run on a Vert.x event loop thread. I see it is running on a NATS thread (nats:3 thread). In my view, the subscriber handler should run on the verticle context that subscribed. Or at least that is how other http servers or messaging clients work with Vert.x.
6 replies


	at io.nats.vertx.impl.NatsStreamImpl.lambda$subscribe$4(NatsStreamImpl.java:179) ~[nats-vertx-interface-1.1.1-beta12.jar:na]
	at io.nats.vertx.impl.NatsStreamImpl.lambda$null$5(NatsStreamImpl.java:194) ~[nats-vertx-interface-1.1.1-beta12.jar:na]
	at io.nats.client.impl.NatsJetStream$AsyncMessageHandler.onMessage(NatsJetStream.java:501) ~[jnats-2.15.6.jar:2.15.6]
	at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:97) ~[jnats-2.15.6.jar:2.15.6]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]


rick

i will create an issue and take a look. Thank you sir.


Thanks


Scott

ok so subscribe handlers require a dispatcher. The dispatcher runs on it's own thread that it gets from the connection executor. You can control the executor from the connection options, but that's it.
There are ways to make your own dispatcher, it's not public scoped but I could do it and maybe make a public hook. You have to manage the dispatcher if you want to control where the subscriber handler runs.
:+1:
1



rick

 does that answer satisfy or do you want us to try to get the dispatcher running inside vertx


rick
  LMK if it is not. I added a number to this issue if you want to talk about it: https://github.com/nats-io/nats-java-vertx-client/issues/44 (You can refer it as 44)

```

**Comment by RichardHightower** [comment]
scott says that i would just have to create a dispatcher on the same package.
